language: node_js

node_js:
  - 8

sudo: required

services:
  - docker

branches:
  only:
  - master

before_install:
  - wget https://raw.githubusercontent.com/owncloud-docker/server/master/Dockerfile
  - wget https://github.com/owncloud/core/archive/c9ea65107399be23a76d43ef3108eca95c08c18b.zip
  - unzip c9ea65107399be23a76d43ef3108eca95c08c18b.zip
  - cd core-c9ea65107399be23a76d43ef3108eca95c08c18b
  - make
  - docker build -t local-oc
  - DOCKER_ID=$(docker run -d -p 8888:80 local-oc)

  - # needed else occ isn't available directly...
  - sleep 5

  - docker inspect $DOCKER_ID
  - docker exec -u www-data $DOCKER_ID ./occ maintenance:install --admin-user="admin" --admin-pass="admin" --database="sqlite"
  - docker exec -u www-data $DOCKER_ID ./occ config:system:set cors.allowed-domains 0 --value http://127.0.0.1:9876
  - docker exec -u www-data $DOCKER_ID ./occ config:system:set cors.allowed-domains 1 --value http://localhost:9876

script:
  - npm run lint
  - sleep 10
  - make test

after_script:
  - codecov
  - docker logs $DOCKER_ID
